# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SuperHero' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SuperHero
  target 'SuperHero-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SuperHeroTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SuperHero-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SuperHero-tvOS


end
